


CREATE USER CISADM IDENTIFIED BY CISADM
DEFAULT TABLESPACE CISTS_01
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;

CREATE ROLE CIS_READ;
CREATE ROLE CIS_USER;

GRANT UNLIMITED TABLESPACE TO CISADM WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO CISADM;
GRANT CREATE DATABASE LINK TO CISADM;
GRANT CONNECT TO CISADM;
GRANT RESOURCE TO CISADM;
GRANT DBA TO CISADM WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO CISADM;
GRANT SELECT ANY DICTIONARY TO CISADM;

CREATE USER CISUSER PROFILE DEFAULT IDENTIFIED BY CISUSER
DEFAULT TABLESPACE CISTS_01
TEMPORARY TABLESPACE TEMP;

GRANT SELECT ANY TABLE TO CISUSER;
GRANT CIS_USER TO CISUSER;
GRANT CIS_READ TO CISUSER;
GRANT CONNECT TO CISUSER;

CREATE USER CISOPR PROFILE DEFAULT IDENTIFIED BY OPRPLUS
DEFAULT TABLESPACE CISTS_01
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT,RESOURCE,EXP_FULL_DATABASE TO CISOPR;

CREATE USER CISREAD IDENTIFIED BY CISREAD
DEFAULT TABLESPACE CISTS_01
TEMPORARY TABLESPACE TEMP;

GRANT SELECT ANY TABLE TO CISREAD;
GRANT CIS_READ TO CISREAD;
GRANT CONNECT TO CISREAD;

spool off
exit;









